# Generated by Django 2.2 on 2021-07-01 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_feedbackcustomers_notificationcustomers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekly_menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monday', models.CharField(blank=True, max_length=200, null=True)),
                ('tuesday', models.CharField(blank=True, max_length=200, null=True)),
                ('wednesday', models.CharField(blank=True, max_length=200, null=True)),
                ('thursday', models.CharField(blank=True, max_length=200, null=True)),
                ('friday', models.CharField(blank=True, max_length=200, null=True)),
                ('saturday', models.CharField(blank=True, max_length=200, null=True)),
                ('sunday', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='accounts.Product')),
            ],
        ),
    ]
